### ISSUE TITLE
adding multiple routes?

### ISSUE THREAD

**Issue by lonnietc** [rtctunnel/rtctunnel#23]
Hello,

I really like the idea of rtctunnel and am wondering if you can add multiple routes through the tunnel?

Additionally, is it possible to set up multiple tunnels in a P2P type topology?

Thanks

**Comment by calebdoxsey** [comment]
Hi @lonnietc . Yes multiple routes are supported. You can use the `add-route` command to do this, though I've admittedly only ever tested with a single route.

And yes it is possible to setup multiple tunnels. You can customize which configuration file is used by rtctunnel and each instance of the app could use a different public identity. Since communication is handled by WebRTC and not via TCP ports there should be no conflict, as long as the routes don't overlap.

As far as P2P goes, since multiple routes are supported you should be able to connect to multiple peers through a single instance of rtctunnel.

Since this app is more of a proof-of-concept I'd highly recommend using a more robust application like Tailscale if you're trying to setup a P2P private network.
